/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CardapioJpaController;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cardapio;

/**
 *
 * @author Thiago
 */
public class TelaCardapio extends javax.swing.JFrame {

    CardapioJpaController daoCardapio;
    /**
     * Creates new form TelaCardapio
     */
    public TelaCardapio() {
        initComponents();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("RestaurantePU");
        daoCardapio = new CardapioJpaController(emf);
        atualizaTabela();
    }
    
    public void atualizaTabela() {
        List<Cardapio> lista = this.daoCardapio.findAll();
        DefaultTableModel tabela = (DefaultTableModel) tabelaCardapio.getModel();
        tabela.setRowCount(0);
        
        for (Cardapio c: lista) {
            Object[] obj = new Object[] {
                c.getIdcardapio(),
                c.getDiacardapio(),  c.getSaladacardapio(), c.getCarboidratocardapio(),
                c.getGraoscardapio(), c.getProteinacardapio(), c.getBebidacardapio()
            };
            tabela.addRow(obj);
        }
    }
    
    public void preencheDado() {
        int linhaSelecionada = tabelaCardapio.getSelectedRow();
        
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        else {
            int codigo = Integer.parseInt(tabelaCardapio.getValueAt(linhaSelecionada, 0).toString());
            Cardapio c = this.daoCardapio.find(codigo);
            tfSalada.setText(c.getSaladacardapio());
            tfCarboidrato.setText(c.getCarboidratocardapio());
            tfGraos.setText(c.getGraoscardapio());
            tfProteina.setText(c.getProteinacardapio());
            tfBebida.setText(c.getBebidacardapio());
            
            // Atualize os botões dos dias da semana
            switch (c.getDiacardapio()) {
                case "SEG" -> tgbtSegunda.setSelected(true);
                case "TER" -> tgbtTerca.setSelected(true);
                case "QUA" -> tgbtQuarta.setSelected(true);
                case "QUI" -> tgbtQuinta.setSelected(true);
                case "SEX" -> tgbtSexta.setSelected(true);
            }
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCardapio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfSalada = new javax.swing.JTextField();
        tfCarboidrato = new javax.swing.JTextField();
        tfBebida = new javax.swing.JTextField();
        tfProteina = new javax.swing.JTextField();
        tfGraos = new javax.swing.JTextField();
        tgbtSegunda = new javax.swing.JToggleButton();
        tgbtTerca = new javax.swing.JToggleButton();
        tgbtQuarta = new javax.swing.JToggleButton();
        tgbtQuinta = new javax.swing.JToggleButton();
        tgbtSexta = new javax.swing.JToggleButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "DIA", "Salada", "Carboidrato", "Grãos", "Proteína", "Bebida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCardapio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCardapioMouseClicked(evt);
            }
        });
        tabelaCardapio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaCardapioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCardapio);
        if (tabelaCardapio.getColumnModel().getColumnCount() > 0) {
            tabelaCardapio.getColumnModel().getColumn(0).setMinWidth(0);
            tabelaCardapio.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabelaCardapio.getColumnModel().getColumn(0).setMaxWidth(0);
            tabelaCardapio.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DIA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Salada");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Carboidrato");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Proteína");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Bebida");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ion--restaurant.png"))); // NOI18N
        jLabel6.setText("icon");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Grãos");

        buttonGroup.add(tgbtSegunda);
        tgbtSegunda.setText("SEG");
        tgbtSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtSegundaActionPerformed(evt);
            }
        });

        buttonGroup.add(tgbtTerca);
        tgbtTerca.setText("TER");
        tgbtTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtTercaActionPerformed(evt);
            }
        });

        buttonGroup.add(tgbtQuarta);
        tgbtQuarta.setText("QUA");
        tgbtQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtQuartaActionPerformed(evt);
            }
        });

        buttonGroup.add(tgbtQuinta);
        tgbtQuinta.setText("QUI");
        tgbtQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtQuintaActionPerformed(evt);
            }
        });

        buttonGroup.add(tgbtSexta);
        tgbtSexta.setText("SEX");
        tgbtSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtSextaActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        jLabel8.setText("RESTAURANTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfBebida, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfCarboidrato, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfSalada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfProteina, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfGraos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tgbtSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tgbtTerca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(tgbtQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(tgbtQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(tgbtSexta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgbtSegunda)
                    .addComponent(tgbtTerca)
                    .addComponent(tgbtQuarta)
                    .addComponent(tgbtQuinta)
                    .addComponent(tgbtSexta)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCarboidrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGraos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfProteina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir)
                    .addComponent(btEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String diacardapio;
    
    private void tgbtSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtSegundaActionPerformed
        if (tgbtSegunda.isSelected()) {
            buttonGroup.clearSelection();
            tgbtSegunda.setSelected(true);
            diacardapio = "SEG";
        }
    }//GEN-LAST:event_tgbtSegundaActionPerformed

    private void tgbtTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtTercaActionPerformed
        if (tgbtTerca.isSelected()) {
            buttonGroup.clearSelection();
            tgbtTerca.setSelected(true);
            diacardapio = "TER";
        }
    }//GEN-LAST:event_tgbtTercaActionPerformed

    private void tgbtQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtQuartaActionPerformed
        if (tgbtQuarta.isSelected()) {
            buttonGroup.clearSelection();
            tgbtQuarta.setSelected(true);
            diacardapio = "QUA";
        }
    }//GEN-LAST:event_tgbtQuartaActionPerformed

    private void tgbtQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtQuintaActionPerformed
        if (tgbtQuinta.isSelected()) {
            buttonGroup.clearSelection();
            tgbtQuinta.setSelected(true);
            diacardapio = "QUI";
        }
    }//GEN-LAST:event_tgbtQuintaActionPerformed

    private void tgbtSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtSextaActionPerformed
        if (tgbtSexta.isSelected()) {
            buttonGroup.clearSelection();
            tgbtSexta.setSelected(true);
            diacardapio = "SEX";
        }
    }//GEN-LAST:event_tgbtSextaActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Cardapio cardapio = new Cardapio();
        cardapio.setDiacardapio(diacardapio);
        cardapio.setSaladacardapio(tfSalada.getText());
        cardapio.setCarboidratocardapio(tfCarboidrato.getText());
        cardapio.setGraoscardapio(tfGraos.getText());
        cardapio.setProteinacardapio(tfProteina.getText());
        cardapio.setBebidacardapio(tfBebida.getText());
        
        try {
            this.daoCardapio.create(cardapio);
            JOptionPane.showMessageDialog(null, "Cardapio criado.");
            atualizaTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro" + e.getMessage());
        }
        
        tfSalada.setText("");
        tfCarboidrato.setText("");
        tfGraos.setText("");
        tfProteina.setText("");
        tfBebida.setText("");
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
       
        int linhaSelecionada = tabelaCardapio.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar");
            return;
        }

        int codigo = Integer.parseInt(tabelaCardapio.getValueAt(linhaSelecionada, 0).toString());
        Cardapio c = this.daoCardapio.find(codigo);

        String diacardapio = "";
        if (tgbtSegunda.isSelected()) {
            diacardapio = "SEG";
        } else if (tgbtTerca.isSelected()) {
            diacardapio = "TER";
        } else if (tgbtQuarta.isSelected()) {
            diacardapio = "QUA";
        } else if (tgbtQuinta.isSelected()) {
            diacardapio = "QUI";
        } else if (tgbtSexta.isSelected()) {
            diacardapio = "SEX";
        }

        c.setDiacardapio(diacardapio);
        c.setSaladacardapio(tfSalada.getText());
        c.setCarboidratocardapio(tfCarboidrato.getText());
        c.setGraoscardapio(tfGraos.getText());
        c.setProteinacardapio(tfProteina.getText());
        c.setBebidacardapio(tfBebida.getText());

        try {
            this.daoCardapio.edit(c);
            JOptionPane.showMessageDialog(null, "Cardápio alterado");
            atualizaTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
        
        tfSalada.setText("");
        tfCarboidrato.setText("");
        tfGraos.setText("");
        tfProteina.setText("");
        tfBebida.setText("");
        

    }//GEN-LAST:event_btEditarActionPerformed

    private void tabelaCardapioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCardapioMouseClicked
        preencheDado();
    }//GEN-LAST:event_tabelaCardapioMouseClicked

    private void tabelaCardapioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaCardapioKeyReleased
        preencheDado();
    }//GEN-LAST:event_tabelaCardapioKeyReleased

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linhaSelecionada = tabelaCardapio.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar");
            return;
        }
        
        int codigo = Integer.parseInt(tabelaCardapio.getValueAt(linhaSelecionada, 0).toString());
        Cardapio c = this.daoCardapio.find(codigo);
        
        try {
            int i = JOptionPane.showConfirmDialog(null, "Deseja excluir essa cadastro?", "Excluir CLiente", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                this.daoCardapio.remove(c);
                JOptionPane.showMessageDialog(null, "Cadastro removido");
                atualizaTabela();
            }
            else {
                JOptionPane.showMessageDialog(null, "Operação Cancelada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro" + e.getMessage());
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCardapio;
    private javax.swing.JTextField tfBebida;
    private javax.swing.JTextField tfCarboidrato;
    private javax.swing.JTextField tfGraos;
    private javax.swing.JTextField tfProteina;
    private javax.swing.JTextField tfSalada;
    private javax.swing.JToggleButton tgbtQuarta;
    private javax.swing.JToggleButton tgbtQuinta;
    private javax.swing.JToggleButton tgbtSegunda;
    private javax.swing.JToggleButton tgbtSexta;
    private javax.swing.JToggleButton tgbtTerca;
    // End of variables declaration//GEN-END:variables
}
